/home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Solver.o /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Solver.or /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Solver.od /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Solver.op: \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Solver.cc \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/Sort.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/Vec.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/IntTypes.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/XAlloc.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Solver.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/Heap.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/Alg.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/utils/Options.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/utils/ParseUtils.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/SolverTypes.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/Map.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/Alloc.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/utils/System.h \
 /usr/lib/openmpi/include/mpi.h \
 /usr/lib/openmpi/include/mpi_portable_platform.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h
/home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Main.o /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Main.or /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Main.od /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Main.op: \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Main.cc \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/utils/System.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/IntTypes.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/utils/ParseUtils.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/utils/Options.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/Vec.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/XAlloc.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Dimacs.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/SolverTypes.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/Alg.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/Map.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/Alloc.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Solver.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/mtl/Heap.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/Solver.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/../mtl/Vec.h \
 /home/thorsten/Documents/ZS/Sortiernetze/github/JCSS/miniSAT_for_Sorting_Networks/core/SolverTypes.h
